/* eslint-disable @next/next/no-img-element */

import type { ComponentPropsWithoutRef } from 'react'

type StaticPictureProps = Omit<
  ComponentPropsWithoutRef<'img'>,
  'src' | 'srcSet' | 'alt'
> & {
  /**
   * Public URL without the generated "-{width}.webp" suffix.
   * Example: /static-images/v1/hero/card-01
   */
  basePath: string
  widths: readonly number[]
  alt: string
}

/**
 * Responsive local image that never calls Vercel's /_next/image transformer.
 *
 * Variants are generated by scripts/generate-static-images.mjs before every
 * production build. The browser still chooses the smallest useful source from
 * srcSet, so disabling billed runtime transformations does not mean serving
 * the original multi-megabyte files.
 */
export default function StaticPicture({
  basePath,
  widths,
  alt,
  decoding = 'async',
  ...props
}: StaticPictureProps) {
  const sortedWidths = [...widths].sort((a, b) => a - b)
  const largestWidth = sortedWidths.at(-1)

  if (!largestWidth) {
    throw new Error('StaticPicture requires at least one generated width.')
  }

  return (
    <img
      {...props}
      src={`${basePath}-${largestWidth}.webp`}
      srcSet={sortedWidths
        .map((width) => `${basePath}-${width}.webp ${width}w`)
        .join(', ')}
      alt={alt}
      decoding={decoding}
    />
  )
}
